name: Build and Push Docker Image

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ai-flashlearn

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub (optional)
        uses: docker/login-action@v2
        with:
          username: trongnguyendt
          password: emduockhenlaembengoanmeomeomeo

      - name: Build Docker image with Python 3.9
        uses: docker/build-push-action@v3
        with:
          push: true  
          tags: trongnguyendt/image_flashlearn_python:latest
          dockerfile: Dockerfile
          cache_from: type=registry,ref=trongnguyendt/image_flashlearn_python:cache
